### ISSUE TITLE
개인적으로 코드 수정 후 컴파일 오류에 관하여

### ISSUE THREAD

**Issue by hotaru0503** [OFox213/DCRanking#1]
디시인사이드 미니갤 적용을 위해 소스코드를 다운받아 코드 몇 자 간단히 수정한 뒤에 VScode로 컴파일하려고 보니 

`MSBUILD : error MSB1011`

 에러가 뜨고 그 다음에 `DCRanking-master.csproj` 파일을 찝어(?) 컴파일하려니 

`error MSB3822: 문자열이 아닌 리소스에는 런타임 시 System.Resources.Extensions 어셈블리가 필요하지만, 이 프로젝트의 참조에서 찾을 수 없습니다.`

라는 에러가 뜨면서 결국 컴파일이 안됩니다.

여러 방도로 해결할 방법을 찾다가 도무지 방법을 모르겠어서 남깁니다.

**Comment by OFox213** [comment]
이 프로젝트의 기본적인 안내입니다.
이 프로젝트는 .Net Framework 4.7.2를 사용합니다. MsBuild 또는 비주얼 스튜디오로 빌드해주셔야 하며, dotnet build 로는 빌드할 수 없습니다.
참고 문서 : [Visual studio build error MSB3822](https://learn.microsoft.com/ko-kr/visualstudio/msbuild/errors/msb3822?view=vs-2022)

질문자님의 답변을 바탕으로 한 안내입니다.
질문자님은 Visual Studio가 아닌 VisualStudio Code로 프로젝트를 빌드하려고 시도하신 것으로 보입니다.
이 프로젝트는 Visual Studio에서 C# Winform 기반으로 제작되었으며 VSCode에서는 폼 수정 및 빌드가 불가합니다.
따라서 VS 2022 버전으로 다시 시도해주시길 바랍니다. 감사합니다.
또한 최근 1.2 업데이트를 진행하면서 미니 갤러리에 대한 댓글 랭킹을 지원하므로 참고해주시길 바랍니다~
https://github.com/OFox213/DCRanking/releases/tag/1.2
