### ISSUE TITLE
1.2 업데이트 미니갤  댓글목록 오류

### ISSUE THREAD

**Issue by hotaru0503** [OFox213/DCRanking#2]
메이저 갤러리, 마이너 갤러리는 이상 없습니다.
미니 갤러리 댓글 집계 데이터 저장이 안 되는듯 합니다.

![스크린샷 2024-02-05 114108](https://github.com/OFox213/DCRanking/assets/76423745/de64526a-546d-481c-b087-d5d1f42ad3a4)

미니갤 predata.json에는 아무것도 저장이 안 되어 있습니다.

**Comment by OFox213** [comment]
미니갤 댓글 수집에 관한 문제를 확인하였습니다.
빠른 시일 내에 원인 조사 후 수정&배포 조치하도록 하겠습니다.

**Comment by OFox213** [comment]
[원인]
미니 갤러리에서는 갤러리 아이디로 댓글 요청시 접두사로 mi$를 사용함.

1.3 버전에서는 미니 갤러리에 대해 댓글 수집이 가능합니다
https://github.com/OFox213/DCRanking/releases/tag/1.3
